### ISSUE TITLE
Temporary fix for #8

### ISSUE THREAD

**Issue by EvitanRelta** [EvitanRelta/markgh#19]
For now, #8 can be fixed by applying the below CSS to every `BulletList` / `OrderedList` TipTap node.
```css
.markdown-body ol.no-list-item-spacing > li > p,
.markdown-body ul.no-list-item-spacing > li > p {
    margin: 0 !important;
}
```

I've yet to figured out how to create an TipTap extension for the `ol` / `ul` element. I've only managed to add the classname to the `li` element in the [`fix-008-list-item-spacing`](https://github.com/EvitanRelta/markgh/tree/fix-008-list-item-spacing) branch.
