### ISSUE TITLE
Incorrect spacing between TipTap's list items

### ISSUE THREAD

**Issue by EvitanRelta** [EvitanRelta/markgh#8]
TipTap editor wraps the contents of `li` tags in `p` tags, as shown:

![](https://user-images.githubusercontent.com/35413456/172410018-ac2356f3-d482-4d4b-a45a-50e070635fca.png)

<br>

which causes the spacing between list items to be bigger, as shown _(left: original, right: TipTap)_:

<br>

<img src="https://user-images.githubusercontent.com/35413456/172408913-4fb78890-f72f-4850-943d-6d56abd1789d.png" height=200 />

**Comment by EvitanRelta** [comment]
Github's markdown seems to allow **BOTH** `li` with an inner `p` tag, as shown:

- item 1
- item 2

#### _markdown_:
```markdown
- item 1
- item 2
```

<br>

and `li` **without** `p`, as shown:

- item 1

- item 2

#### _markdown_:
```markdown
- item 1

- item 2
```

<hr>

Thus, removing the top/bottom margins of  `p` in `li` via CSS _(shown below)_ to "emulate" the "`li` without `p`" spacing, will have problems later when trying to render "`li` with `p`" spacings

```css
.markdown-body li > p {
  margin-top: 0;
  margin-bottom: 0;
}
```
<hr>
Perhaps, having an option to add/remove the inbetween-list-item spacing, and have it controlled by adding a class to the `li` element like this:

```css
li.no-list-item-spacing > p {
  margin-top: 0;
  margin-bottom: 0;
}
```

```html
<li class="no-list-item-spacing">
  <p>item</p>
</li>
```
